### ISSUE TITLE
Paddle is not drawn in window

### ISSUE THREAD

**Issue by christoph-fricke** [finia2NA/project-lytehouse#11]
When starting the program the paddle is outside of the window area. It first gets visible when resizing the window in the y position

**Comment by finia2NA** [comment]
Don't know why the Window didn't properly rescale, it's written pretty clearly in the init() of the new Client View that it should be 560x840px.
`public void init() {
		...
		top.setSize(560, 840);
		top.setTitle("Breakout - A story of a stranded BPaddle");
                ...
	}`
My guess is Windows scaling and the ACM don't work together very well.
Anyways, it's not gamebreaking and can be solved by manually rescaling ^^
